name: vensurelints
description: vensure coding standard lints for mobile applications.
version: 1.0.3
repository: https://github.com/abhijithsabudev/vensurelints.git

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  lints: ^4.0.0

dev_dependencies:
  test: ^1.24.0
